{{- if and .Values.frontend.enabled .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample-app.name" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    component: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.frontend.ingress.host }}
    {{- if .Values.frontend.ingress.protocol | eq "https" }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: 'true'
    {{- end }}
    {{- if and (.Values.frontend.ingress.protocol | eq "https") (.Values.frontend.ingress.ingressClassName | eq "nginx") }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    {{- end }}
    {{- if .Values.frontend.ingress.protocol | eq "https" }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    {{- end }}
spec:
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName | default "nginx" }}
  {{- if .Values.frontend.ingress.protocol | eq "https" }}
  tls:
    - hosts:
      - "{{ .Values.frontend.ingress.host }}"
      secretName: "tls-{{ include "sample-app.name" . }}-frontend"
  {{- end }}
  rules:
  - host: "{{ .Values.frontend.ingress.host }}"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "sample-app.name" . }}-frontend
              port:
                number: {{ .Values.frontend.port }}
{{- end }}
