# Global variables
microservice:
  name: ai-morality-final-project-frontend
  tag: 1.0.0
  environment: dev
  port: 3000
  healthCheckPath: /
  logLevel: INFO
  protocol: http
  replicas: 1

resources:
  memory: 256Mi
  cpu: 100m

# Image variables
imagePath: ghcr.io/stavco9/ai-morality-final-project/frontend

# Ingress variables
ingress:
  enabled: true
  protocol: https
  ingressClassName: nginx
  host: ai-judge.k8s.stav-devops.eu-central-1.pre-prod.stavco9.com

# Secrets variables
secrets: []
